### ISSUE TITLE
建议给www.innoreader.com也加上（多个n）

### ISSUE THREAD

**Issue by winter60** [maboloshi/UserScripts#2]
我试了 https://www.inoreader.com/可以， 但https://www.innoreader.com/不可以。谢谢啦

**Comment by winter60** [comment]
一般情况下没qiang，用不了少个n的。

**Comment by maboloshi** [comment]
已更新 请尝试一下效果

**Comment by winter60** [comment]
> 已更新 请尝试一下效果

太感谢作者迅猛更新。不过有一点小问题， 图片部分成功显示出来了。给您对比一下
![部分成功显示图片](https://user-images.githubusercontent.com/23653326/162107491-08bb6e65-1992-46c5-9e50-637a007b7d46.gif)

**Comment by winter60** [comment]
> > 已更新 请尝试一下效果
> 
> 太感谢作者迅猛更新。不过有一点小问题， 图片部分成功显示出来了。给您对比一下 ![部分成功显示图片](https://user-images.githubusercontent.com/23653326/162107491-08bb6e65-1992-46c5-9e50-637a007b7d46.gif)

不好意思，作者大大，是缓存的问题。我清理了浏览器缓存好像就行了，不好意思哟~
